// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Input
	TransForm
	Vector3
	Quaternion
	Position
	CallFuncInfo
	BasicType
	Error
	Empty
	RoomPrepareView
	GameFrame
	RoomView
	HomeView
	RoomInfoView
	RoomList
	SessionInfo
	Success
	AttrSetting
	SessionKey
	ServerInfo
	LoginInput
	RegistInput
	UserInfo
	UserState
	RoomInfo
	Character
	Color
	Equipment
	Ability
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SessionInfo_SessionState int32

const (
	SessionInfo_NoSession   SessionInfo_SessionState = 0
	SessionInfo_Guest       SessionInfo_SessionState = 1
	SessionInfo_UserIdle    SessionInfo_SessionState = 2
	SessionInfo_UserInRoom  SessionInfo_SessionState = 3
	SessionInfo_WaitToStart SessionInfo_SessionState = 4
	SessionInfo_Playing     SessionInfo_SessionState = 5
)

var SessionInfo_SessionState_name = map[int32]string{
	0: "NoSession",
	1: "Guest",
	2: "UserIdle",
	3: "UserInRoom",
	4: "WaitToStart",
	5: "Playing",
}
var SessionInfo_SessionState_value = map[string]int32{
	"NoSession":   0,
	"Guest":       1,
	"UserIdle":    2,
	"UserInRoom":  3,
	"WaitToStart": 4,
	"Playing":     5,
}

func (x SessionInfo_SessionState) String() string {
	return proto.EnumName(SessionInfo_SessionState_name, int32(x))
}
func (SessionInfo_SessionState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{15, 0} }

type SessionInfo_SessionCapacity int32

const (
	SessionInfo_GM         SessionInfo_SessionCapacity = 0
	SessionInfo_RoomMaster SessionInfo_SessionCapacity = 1
	SessionInfo_RoomClient SessionInfo_SessionCapacity = 2
	SessionInfo_None       SessionInfo_SessionCapacity = 3
)

var SessionInfo_SessionCapacity_name = map[int32]string{
	0: "GM",
	1: "RoomMaster",
	2: "RoomClient",
	3: "None",
}
var SessionInfo_SessionCapacity_value = map[string]int32{
	"GM":         0,
	"RoomMaster": 1,
	"RoomClient": 2,
	"None":       3,
}

func (x SessionInfo_SessionCapacity) String() string {
	return proto.EnumName(SessionInfo_SessionCapacity_name, int32(x))
}
func (SessionInfo_SessionCapacity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15, 1}
}

type ServerInfo_Type int32

const (
	ServerInfo_GameServer  ServerInfo_Type = 0
	ServerInfo_AgentServer ServerInfo_Type = 1
)

var ServerInfo_Type_name = map[int32]string{
	0: "GameServer",
	1: "AgentServer",
}
var ServerInfo_Type_value = map[string]int32{
	"GameServer":  0,
	"AgentServer": 1,
}

func (x ServerInfo_Type) String() string {
	return proto.EnumName(ServerInfo_Type_name, int32(x))
}
func (ServerInfo_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{19, 0} }

type UserState_UserStatus int32

const (
	UserState_OnCreating UserState_UserStatus = 0
	UserState_Login      UserState_UserStatus = 1
	UserState_Offline    UserState_UserStatus = 2
	UserState_OnPlaying  UserState_UserStatus = 3
)

var UserState_UserStatus_name = map[int32]string{
	0: "OnCreating",
	1: "Login",
	2: "Offline",
	3: "OnPlaying",
}
var UserState_UserStatus_value = map[string]int32{
	"OnCreating": 0,
	"Login":      1,
	"Offline":    2,
	"OnPlaying":  3,
}

func (x UserState_UserStatus) String() string {
	return proto.EnumName(UserState_UserStatus_name, int32(x))
}
func (UserState_UserStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{23, 0} }

type RoomInfo_RoomStatus int32

const (
	RoomInfo_Preparing RoomInfo_RoomStatus = 0
	RoomInfo_OnPlaying RoomInfo_RoomStatus = 1
	RoomInfo_Ending    RoomInfo_RoomStatus = 2
)

var RoomInfo_RoomStatus_name = map[int32]string{
	0: "Preparing",
	1: "OnPlaying",
	2: "Ending",
}
var RoomInfo_RoomStatus_value = map[string]int32{
	"Preparing": 0,
	"OnPlaying": 1,
	"Ending":    2,
}

func (x RoomInfo_RoomStatus) String() string {
	return proto.EnumName(RoomInfo_RoomStatus_name, int32(x))
}
func (RoomInfo_RoomStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{24, 0} }

type Input struct {
	UserId     int64   `protobuf:"varint,1,opt,name=UserId,json=userId" json:"UserId,omitempty"`
	H_Movement float32 `protobuf:"fixed32,2,opt,name=H_Movement,json=hMovement" json:"H_Movement,omitempty"`
	V_Movement float32 `protobuf:"fixed32,3,opt,name=V_Movement,json=vMovement" json:"V_Movement,omitempty"`
	SkillName  string  `protobuf:"bytes,5,opt,name=SkillName,json=skillName" json:"SkillName,omitempty"`
	SkillForce float32 `protobuf:"fixed32,4,opt,name=SkillForce,json=skillForce" json:"SkillForce,omitempty"`
	TimeStamp  int64   `protobuf:"varint,6,opt,name=TimeStamp,json=timeStamp" json:"TimeStamp,omitempty"`
	RunnigNo   int64   `protobuf:"varint,7,opt,name=RunnigNo,json=runnigNo" json:"RunnigNo,omitempty"`
}

func (m *Input) Reset()                    { *m = Input{} }
func (m *Input) String() string            { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()               {}
func (*Input) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Input) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Input) GetH_Movement() float32 {
	if m != nil {
		return m.H_Movement
	}
	return 0
}

func (m *Input) GetV_Movement() float32 {
	if m != nil {
		return m.V_Movement
	}
	return 0
}

func (m *Input) GetSkillName() string {
	if m != nil {
		return m.SkillName
	}
	return ""
}

func (m *Input) GetSkillForce() float32 {
	if m != nil {
		return m.SkillForce
	}
	return 0
}

func (m *Input) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *Input) GetRunnigNo() int64 {
	if m != nil {
		return m.RunnigNo
	}
	return 0
}

type TransForm struct {
	Position *Vector3    `protobuf:"bytes,1,opt,name=Position,json=position" json:"Position,omitempty"`
	Rotation *Quaternion `protobuf:"bytes,2,opt,name=Rotation,json=rotation" json:"Rotation,omitempty"`
}

func (m *TransForm) Reset()                    { *m = TransForm{} }
func (m *TransForm) String() string            { return proto.CompactTextString(m) }
func (*TransForm) ProtoMessage()               {}
func (*TransForm) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TransForm) GetPosition() *Vector3 {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *TransForm) GetRotation() *Quaternion {
	if m != nil {
		return m.Rotation
	}
	return nil
}

type Vector3 struct {
	X float64 `protobuf:"fixed64,1,opt,name=X,json=x" json:"X,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=Y,json=y" json:"Y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=Z,json=z" json:"Z,omitempty"`
}

func (m *Vector3) Reset()                    { *m = Vector3{} }
func (m *Vector3) String() string            { return proto.CompactTextString(m) }
func (*Vector3) ProtoMessage()               {}
func (*Vector3) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Vector3) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector3) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Vector3) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Quaternion struct {
	X float64 `protobuf:"fixed64,1,opt,name=X,json=x" json:"X,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=Y,json=y" json:"Y,omitempty"`
	Z float64 `protobuf:"fixed64,3,opt,name=Z,json=z" json:"Z,omitempty"`
	W float64 `protobuf:"fixed64,4,opt,name=W,json=w" json:"W,omitempty"`
}

func (m *Quaternion) Reset()                    { *m = Quaternion{} }
func (m *Quaternion) String() string            { return proto.CompactTextString(m) }
func (*Quaternion) ProtoMessage()               {}
func (*Quaternion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Quaternion) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Quaternion) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Quaternion) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *Quaternion) GetW() float64 {
	if m != nil {
		return m.W
	}
	return 0
}

type Position struct {
	PosMap    map[int64]*TransForm `protobuf:"bytes,1,rep,name=PosMap,json=posMap" json:"PosMap,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeStamp int64                `protobuf:"varint,2,opt,name=TimeStamp,json=timeStamp" json:"TimeStamp,omitempty"`
}

func (m *Position) Reset()                    { *m = Position{} }
func (m *Position) String() string            { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()               {}
func (*Position) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Position) GetPosMap() map[int64]*TransForm {
	if m != nil {
		return m.PosMap
	}
	return nil
}

func (m *Position) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

type CallFuncInfo struct {
	RunnigNo  string                 `protobuf:"bytes,1,opt,name=RunnigNo,json=runnigNo" json:"RunnigNo,omitempty"`
	TargetId  int64                  `protobuf:"varint,2,opt,name=TargetId,json=targetId" json:"TargetId,omitempty"`
	FromId    int64                  `protobuf:"varint,4,opt,name=FromId,json=fromId" json:"FromId,omitempty"`
	TimeStamp int64                  `protobuf:"varint,5,opt,name=TimeStamp,json=timeStamp" json:"TimeStamp,omitempty"`
	Func      string                 `protobuf:"bytes,6,opt,name=Func,json=func" json:"Func,omitempty"`
	FromPos   *TransForm             `protobuf:"bytes,7,opt,name=FromPos,json=fromPos" json:"FromPos,omitempty"`
	ToPos     *TransForm             `protobuf:"bytes,8,opt,name=ToPos,json=toPos" json:"ToPos,omitempty"`
	Value     float32                `protobuf:"fixed32,9,opt,name=Value,json=value" json:"Value,omitempty"`
	Param     []*google_protobuf.Any `protobuf:"bytes,10,rep,name=Param,json=param" json:"Param,omitempty"`
	Params    []*BasicType           `protobuf:"bytes,11,rep,name=Params,json=params" json:"Params,omitempty"`
}

func (m *CallFuncInfo) Reset()                    { *m = CallFuncInfo{} }
func (m *CallFuncInfo) String() string            { return proto.CompactTextString(m) }
func (*CallFuncInfo) ProtoMessage()               {}
func (*CallFuncInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CallFuncInfo) GetRunnigNo() string {
	if m != nil {
		return m.RunnigNo
	}
	return ""
}

func (m *CallFuncInfo) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *CallFuncInfo) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *CallFuncInfo) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *CallFuncInfo) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

func (m *CallFuncInfo) GetFromPos() *TransForm {
	if m != nil {
		return m.FromPos
	}
	return nil
}

func (m *CallFuncInfo) GetToPos() *TransForm {
	if m != nil {
		return m.ToPos
	}
	return nil
}

func (m *CallFuncInfo) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *CallFuncInfo) GetParam() []*google_protobuf.Any {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *CallFuncInfo) GetParams() []*BasicType {
	if m != nil {
		return m.Params
	}
	return nil
}

type BasicType struct {
	// Types that are valid to be assigned to Data:
	//	*BasicType_S
	//	*BasicType_L
	//	*BasicType_F
	//	*BasicType_I
	//	*BasicType_B
	//	*BasicType_D
	//	*BasicType_A
	Data isBasicType_Data `protobuf_oneof:"Data"`
}

func (m *BasicType) Reset()                    { *m = BasicType{} }
func (m *BasicType) String() string            { return proto.CompactTextString(m) }
func (*BasicType) ProtoMessage()               {}
func (*BasicType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type isBasicType_Data interface {
	isBasicType_Data()
}

type BasicType_S struct {
	S string `protobuf:"bytes,1,opt,name=S,json=s,oneof"`
}
type BasicType_L struct {
	L int64 `protobuf:"varint,2,opt,name=L,json=l,oneof"`
}
type BasicType_F struct {
	F float32 `protobuf:"fixed32,3,opt,name=F,json=f,oneof"`
}
type BasicType_I struct {
	I int32 `protobuf:"varint,4,opt,name=I,json=i,oneof"`
}
type BasicType_B struct {
	B bool `protobuf:"varint,5,opt,name=B,json=b,oneof"`
}
type BasicType_D struct {
	D float64 `protobuf:"fixed64,6,opt,name=D,json=d,oneof"`
}
type BasicType_A struct {
	A *google_protobuf.Any `protobuf:"bytes,7,opt,name=A,json=a,oneof"`
}

func (*BasicType_S) isBasicType_Data() {}
func (*BasicType_L) isBasicType_Data() {}
func (*BasicType_F) isBasicType_Data() {}
func (*BasicType_I) isBasicType_Data() {}
func (*BasicType_B) isBasicType_Data() {}
func (*BasicType_D) isBasicType_Data() {}
func (*BasicType_A) isBasicType_Data() {}

func (m *BasicType) GetData() isBasicType_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BasicType) GetS() string {
	if x, ok := m.GetData().(*BasicType_S); ok {
		return x.S
	}
	return ""
}

func (m *BasicType) GetL() int64 {
	if x, ok := m.GetData().(*BasicType_L); ok {
		return x.L
	}
	return 0
}

func (m *BasicType) GetF() float32 {
	if x, ok := m.GetData().(*BasicType_F); ok {
		return x.F
	}
	return 0
}

func (m *BasicType) GetI() int32 {
	if x, ok := m.GetData().(*BasicType_I); ok {
		return x.I
	}
	return 0
}

func (m *BasicType) GetB() bool {
	if x, ok := m.GetData().(*BasicType_B); ok {
		return x.B
	}
	return false
}

func (m *BasicType) GetD() float64 {
	if x, ok := m.GetData().(*BasicType_D); ok {
		return x.D
	}
	return 0
}

func (m *BasicType) GetA() *google_protobuf.Any {
	if x, ok := m.GetData().(*BasicType_A); ok {
		return x.A
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*BasicType) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _BasicType_OneofMarshaler, _BasicType_OneofUnmarshaler, _BasicType_OneofSizer, []interface{}{
		(*BasicType_S)(nil),
		(*BasicType_L)(nil),
		(*BasicType_F)(nil),
		(*BasicType_I)(nil),
		(*BasicType_B)(nil),
		(*BasicType_D)(nil),
		(*BasicType_A)(nil),
	}
}

func _BasicType_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*BasicType)
	// Data
	switch x := m.Data.(type) {
	case *BasicType_S:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.S)
	case *BasicType_L:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.L))
	case *BasicType_F:
		b.EncodeVarint(3<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.F)))
	case *BasicType_I:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.I))
	case *BasicType_B:
		t := uint64(0)
		if x.B {
			t = 1
		}
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *BasicType_D:
		b.EncodeVarint(6<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.D))
	case *BasicType_A:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.A); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("BasicType.Data has unexpected type %T", x)
	}
	return nil
}

func _BasicType_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*BasicType)
	switch tag {
	case 1: // Data.S
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Data = &BasicType_S{x}
		return true, err
	case 2: // Data.L
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Data = &BasicType_L{int64(x)}
		return true, err
	case 3: // Data.F
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Data = &BasicType_F{math.Float32frombits(uint32(x))}
		return true, err
	case 4: // Data.I
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Data = &BasicType_I{int32(x)}
		return true, err
	case 5: // Data.B
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Data = &BasicType_B{x != 0}
		return true, err
	case 6: // Data.D
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Data = &BasicType_D{math.Float64frombits(x)}
		return true, err
	case 7: // Data.A
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf.Any)
		err := b.DecodeMessage(msg)
		m.Data = &BasicType_A{msg}
		return true, err
	default:
		return false, nil
	}
}

func _BasicType_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*BasicType)
	// Data
	switch x := m.Data.(type) {
	case *BasicType_S:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.S)))
		n += len(x.S)
	case *BasicType_L:
		n += proto.SizeVarint(2<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.L))
	case *BasicType_F:
		n += proto.SizeVarint(3<<3 | proto.WireFixed32)
		n += 4
	case *BasicType_I:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.I))
	case *BasicType_B:
		n += proto.SizeVarint(5<<3 | proto.WireVarint)
		n += 1
	case *BasicType_D:
		n += proto.SizeVarint(6<<3 | proto.WireFixed64)
		n += 8
	case *BasicType_A:
		s := proto.Size(x.A)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Error struct {
	ErrType  string `protobuf:"bytes,1,opt,name=ErrType,json=errType" json:"ErrType,omitempty"`
	ErrMsg   string `protobuf:"bytes,2,opt,name=ErrMsg,json=errMsg" json:"ErrMsg,omitempty"`
	RunnigNo string `protobuf:"bytes,3,opt,name=RunnigNo,json=runnigNo" json:"RunnigNo,omitempty"`
	FromId   int64  `protobuf:"varint,4,opt,name=FromId,json=fromId" json:"FromId,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Error) GetErrType() string {
	if m != nil {
		return m.ErrType
	}
	return ""
}

func (m *Error) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Error) GetRunnigNo() string {
	if m != nil {
		return m.RunnigNo
	}
	return ""
}

func (m *Error) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type RoomPrepareView struct {
}

func (m *RoomPrepareView) Reset()                    { *m = RoomPrepareView{} }
func (m *RoomPrepareView) String() string            { return proto.CompactTextString(m) }
func (*RoomPrepareView) ProtoMessage()               {}
func (*RoomPrepareView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type GameFrame struct {
}

func (m *GameFrame) Reset()                    { *m = GameFrame{} }
func (m *GameFrame) String() string            { return proto.CompactTextString(m) }
func (*GameFrame) ProtoMessage()               {}
func (*GameFrame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type RoomView struct {
}

func (m *RoomView) Reset()                    { *m = RoomView{} }
func (m *RoomView) String() string            { return proto.CompactTextString(m) }
func (*RoomView) ProtoMessage()               {}
func (*RoomView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type HomeView struct {
}

func (m *HomeView) Reset()                    { *m = HomeView{} }
func (m *HomeView) String() string            { return proto.CompactTextString(m) }
func (*HomeView) ProtoMessage()               {}
func (*HomeView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type RoomInfoView struct {
}

func (m *RoomInfoView) Reset()                    { *m = RoomInfoView{} }
func (m *RoomInfoView) String() string            { return proto.CompactTextString(m) }
func (*RoomInfoView) ProtoMessage()               {}
func (*RoomInfoView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type RoomList struct {
	Item []*RoomInfo `protobuf:"bytes,1,rep,name=item" json:"item,omitempty"`
}

func (m *RoomList) Reset()                    { *m = RoomList{} }
func (m *RoomList) String() string            { return proto.CompactTextString(m) }
func (*RoomList) ProtoMessage()               {}
func (*RoomList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RoomList) GetItem() []*RoomInfo {
	if m != nil {
		return m.Item
	}
	return nil
}

type SessionInfo struct {
	State    SessionInfo_SessionState    `protobuf:"varint,1,opt,name=State,json=state,enum=msg.SessionInfo_SessionState" json:"State,omitempty"`
	Capacity SessionInfo_SessionCapacity `protobuf:"varint,2,opt,name=Capacity,json=capacity,enum=msg.SessionInfo_SessionCapacity" json:"Capacity,omitempty"`
	Uuid     int64                       `protobuf:"varint,5,opt,name=Uuid,json=uuid" json:"Uuid,omitempty"`
	Key      *SessionKey                 `protobuf:"bytes,3,opt,name=Key,json=key" json:"Key,omitempty"`
	UserInfo *UserInfo                   `protobuf:"bytes,4,opt,name=UserInfo,json=userInfo" json:"UserInfo,omitempty"`
}

func (m *SessionInfo) Reset()                    { *m = SessionInfo{} }
func (m *SessionInfo) String() string            { return proto.CompactTextString(m) }
func (*SessionInfo) ProtoMessage()               {}
func (*SessionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SessionInfo) GetState() SessionInfo_SessionState {
	if m != nil {
		return m.State
	}
	return SessionInfo_NoSession
}

func (m *SessionInfo) GetCapacity() SessionInfo_SessionCapacity {
	if m != nil {
		return m.Capacity
	}
	return SessionInfo_GM
}

func (m *SessionInfo) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *SessionInfo) GetKey() *SessionKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SessionInfo) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

type Success struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *Success) Reset()                    { *m = Success{} }
func (m *Success) String() string            { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()               {}
func (*Success) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Success) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type AttrSetting struct {
	Method string `protobuf:"bytes,1,opt,name=Method,json=method" json:"Method,omitempty"`
	Key    string `protobuf:"bytes,2,opt,name=Key,json=key" json:"Key,omitempty"`
	Value  string `protobuf:"bytes,3,opt,name=Value,json=value" json:"Value,omitempty"`
}

func (m *AttrSetting) Reset()                    { *m = AttrSetting{} }
func (m *AttrSetting) String() string            { return proto.CompactTextString(m) }
func (*AttrSetting) ProtoMessage()               {}
func (*AttrSetting) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *AttrSetting) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *AttrSetting) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AttrSetting) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SessionKey struct {
	Value string `protobuf:"bytes,1,opt,name=Value,json=value" json:"Value,omitempty"`
}

func (m *SessionKey) Reset()                    { *m = SessionKey{} }
func (m *SessionKey) String() string            { return proto.CompactTextString(m) }
func (*SessionKey) ProtoMessage()               {}
func (*SessionKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *SessionKey) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ServerInfo struct {
	ServerType ServerInfo_Type `protobuf:"varint,1,opt,name=ServerType,json=serverType,enum=msg.ServerInfo_Type" json:"ServerType,omitempty"`
	PublicKey  string          `protobuf:"bytes,2,opt,name=PublicKey,json=publicKey" json:"PublicKey,omitempty"`
	Port       string          `protobuf:"bytes,3,opt,name=Port,json=port" json:"Port,omitempty"`
	Addr       string          `protobuf:"bytes,4,opt,name=Addr,json=addr" json:"Addr,omitempty"`
	SessionKey *SessionKey     `protobuf:"bytes,5,opt,name=SessionKey,json=sessionKey" json:"SessionKey,omitempty"`
	MaxConn    int64           `protobuf:"varint,6,opt,name=MaxConn,json=maxConn" json:"MaxConn,omitempty"`
	NowConn    int64           `protobuf:"varint,7,opt,name=NowConn,json=nowConn" json:"NowConn,omitempty"`
}

func (m *ServerInfo) Reset()                    { *m = ServerInfo{} }
func (m *ServerInfo) String() string            { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()               {}
func (*ServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ServerInfo) GetServerType() ServerInfo_Type {
	if m != nil {
		return m.ServerType
	}
	return ServerInfo_GameServer
}

func (m *ServerInfo) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *ServerInfo) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *ServerInfo) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ServerInfo) GetSessionKey() *SessionKey {
	if m != nil {
		return m.SessionKey
	}
	return nil
}

func (m *ServerInfo) GetMaxConn() int64 {
	if m != nil {
		return m.MaxConn
	}
	return 0
}

func (m *ServerInfo) GetNowConn() int64 {
	if m != nil {
		return m.NowConn
	}
	return 0
}

type LoginInput struct {
	UserName string `protobuf:"bytes,1,opt,name=UserName,json=userName" json:"UserName,omitempty"`
	Pswd     string `protobuf:"bytes,2,opt,name=Pswd,json=pswd" json:"Pswd,omitempty"`
}

func (m *LoginInput) Reset()                    { *m = LoginInput{} }
func (m *LoginInput) String() string            { return proto.CompactTextString(m) }
func (*LoginInput) ProtoMessage()               {}
func (*LoginInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *LoginInput) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginInput) GetPswd() string {
	if m != nil {
		return m.Pswd
	}
	return ""
}

type RegistInput struct {
	UserName string `protobuf:"bytes,1,opt,name=UserName,json=userName" json:"UserName,omitempty"`
	Pswd     string `protobuf:"bytes,2,opt,name=Pswd,json=pswd" json:"Pswd,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=Email,json=email" json:"Email,omitempty"`
}

func (m *RegistInput) Reset()                    { *m = RegistInput{} }
func (m *RegistInput) String() string            { return proto.CompactTextString(m) }
func (*RegistInput) ProtoMessage()               {}
func (*RegistInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *RegistInput) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *RegistInput) GetPswd() string {
	if m != nil {
		return m.Pswd
	}
	return ""
}

func (m *RegistInput) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserInfo struct {
	UserName      string               `protobuf:"bytes,1,opt,name=UserName,json=userName" json:"UserName,omitempty"`
	Uuid          int64                `protobuf:"varint,2,opt,name=Uuid,json=uuid" json:"Uuid,omitempty"`
	OwnCharacter  map[int64]*Character `protobuf:"bytes,3,rep,name=OwnCharacter,json=ownCharacter" json:"OwnCharacter,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UsedCharacter int64                `protobuf:"varint,4,opt,name=UsedCharacter,json=usedCharacter" json:"UsedCharacter,omitempty"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *UserInfo) GetOwnCharacter() map[int64]*Character {
	if m != nil {
		return m.OwnCharacter
	}
	return nil
}

func (m *UserInfo) GetUsedCharacter() int64 {
	if m != nil {
		return m.UsedCharacter
	}
	return 0
}

type UserState struct {
	State UserState_UserStatus `protobuf:"varint,1,opt,name=State,json=state,enum=msg.UserState_UserStatus" json:"State,omitempty"`
}

func (m *UserState) Reset()                    { *m = UserState{} }
func (m *UserState) String() string            { return proto.CompactTextString(m) }
func (*UserState) ProtoMessage()               {}
func (*UserState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *UserState) GetState() UserState_UserStatus {
	if m != nil {
		return m.State
	}
	return UserState_OnCreating
}

type RoomInfo struct {
	Uuid            int64               `protobuf:"varint,1,opt,name=Uuid,json=uuid" json:"Uuid,omitempty"`
	Name            string              `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name,omitempty"`
	GameType        string              `protobuf:"bytes,3,opt,name=GameType,json=gameType" json:"GameType,omitempty"`
	OwnerUuid       int64               `protobuf:"varint,4,opt,name=OwnerUuid,json=ownerUuid" json:"OwnerUuid,omitempty"`
	UserInRoom      map[int64]*UserInfo `protobuf:"bytes,5,rep,name=UserInRoom,json=userInRoom" json:"UserInRoom,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ReadyUser       map[int64]bool      `protobuf:"bytes,6,rep,name=ReadyUser,json=readyUser" json:"ReadyUser,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Status          RoomInfo_RoomStatus `protobuf:"varint,7,opt,name=Status,json=status,enum=msg.RoomInfo_RoomStatus" json:"Status,omitempty"`
	LeftMilliSecond int64               `protobuf:"varint,8,opt,name=LeftMilliSecond,json=leftMilliSecond" json:"LeftMilliSecond,omitempty"`
}

func (m *RoomInfo) Reset()                    { *m = RoomInfo{} }
func (m *RoomInfo) String() string            { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()               {}
func (*RoomInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *RoomInfo) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *RoomInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoomInfo) GetGameType() string {
	if m != nil {
		return m.GameType
	}
	return ""
}

func (m *RoomInfo) GetOwnerUuid() int64 {
	if m != nil {
		return m.OwnerUuid
	}
	return 0
}

func (m *RoomInfo) GetUserInRoom() map[int64]*UserInfo {
	if m != nil {
		return m.UserInRoom
	}
	return nil
}

func (m *RoomInfo) GetReadyUser() map[int64]bool {
	if m != nil {
		return m.ReadyUser
	}
	return nil
}

func (m *RoomInfo) GetStatus() RoomInfo_RoomStatus {
	if m != nil {
		return m.Status
	}
	return RoomInfo_Preparing
}

func (m *RoomInfo) GetLeftMilliSecond() int64 {
	if m != nil {
		return m.LeftMilliSecond
	}
	return 0
}

// character 即是沒有實體之腳色
// entity 則藉由character來初始化
type Character struct {
	Uuid          int64   `protobuf:"varint,1,opt,name=Uuid,json=uuid" json:"Uuid,omitempty"`
	CharacterType string  `protobuf:"bytes,2,opt,name=CharacterType,json=characterType" json:"CharacterType,omitempty"`
	Name          string  `protobuf:"bytes,3,opt,name=Name,json=name" json:"Name,omitempty"`
	Color         *Color  `protobuf:"bytes,4,opt,name=Color,json=color" json:"Color,omitempty"`
	Level         int32   `protobuf:"varint,5,opt,name=Level,json=level" json:"Level,omitempty"`
	Exp           int32   `protobuf:"varint,6,opt,name=Exp,json=exp" json:"Exp,omitempty"`
	MaxHealth     float32 `protobuf:"fixed32,10,opt,name=MaxHealth,json=maxHealth" json:"MaxHealth,omitempty"`
	// 基本能力值
	Ability      *Ability             `protobuf:"bytes,7,opt,name=Ability,json=ability" json:"Ability,omitempty"`
	EquipmentMap map[int64]*Equipment `protobuf:"bytes,8,rep,name=EquipmentMap,json=equipmentMap" json:"EquipmentMap,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 戰鬥時添加的狀態
	Attr map[string]float32 `protobuf:"bytes,9,rep,name=Attr,json=attr" json:"Attr,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
}

func (m *Character) Reset()                    { *m = Character{} }
func (m *Character) String() string            { return proto.CompactTextString(m) }
func (*Character) ProtoMessage()               {}
func (*Character) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *Character) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *Character) GetCharacterType() string {
	if m != nil {
		return m.CharacterType
	}
	return ""
}

func (m *Character) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Character) GetColor() *Color {
	if m != nil {
		return m.Color
	}
	return nil
}

func (m *Character) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Character) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *Character) GetMaxHealth() float32 {
	if m != nil {
		return m.MaxHealth
	}
	return 0
}

func (m *Character) GetAbility() *Ability {
	if m != nil {
		return m.Ability
	}
	return nil
}

func (m *Character) GetEquipmentMap() map[int64]*Equipment {
	if m != nil {
		return m.EquipmentMap
	}
	return nil
}

func (m *Character) GetAttr() map[string]float32 {
	if m != nil {
		return m.Attr
	}
	return nil
}

type Color struct {
	R int32 `protobuf:"varint,1,opt,name=R,json=r" json:"R,omitempty"`
	G int32 `protobuf:"varint,2,opt,name=G,json=g" json:"G,omitempty"`
	B int32 `protobuf:"varint,3,opt,name=B,json=b" json:"B,omitempty"`
}

func (m *Color) Reset()                    { *m = Color{} }
func (m *Color) String() string            { return proto.CompactTextString(m) }
func (*Color) ProtoMessage()               {}
func (*Color) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *Color) GetR() int32 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *Color) GetG() int32 {
	if m != nil {
		return m.G
	}
	return 0
}

func (m *Color) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type Equipment struct {
	Name      string   `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Type      string   `protobuf:"bytes,2,opt,name=Type,json=type" json:"Type,omitempty"`
	Uuid      int64    `protobuf:"varint,3,opt,name=Uuid,json=uuid" json:"Uuid,omitempty"`
	Color     *Color   `protobuf:"bytes,4,opt,name=Color,json=color" json:"Color,omitempty"`
	Ability   *Ability `protobuf:"bytes,5,opt,name=Ability,json=ability" json:"Ability,omitempty"`
	CD        int32    `protobuf:"varint,6,opt,name=CD,json=cD" json:"CD,omitempty"`
	Usable    int32    `protobuf:"varint,7,opt,name=Usable,json=usable" json:"Usable,omitempty"`
	Inventory int32    `protobuf:"varint,8,opt,name=Inventory,json=inventory" json:"Inventory,omitempty"`
}

func (m *Equipment) Reset()                    { *m = Equipment{} }
func (m *Equipment) String() string            { return proto.CompactTextString(m) }
func (*Equipment) ProtoMessage()               {}
func (*Equipment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *Equipment) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Equipment) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Equipment) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *Equipment) GetColor() *Color {
	if m != nil {
		return m.Color
	}
	return nil
}

func (m *Equipment) GetAbility() *Ability {
	if m != nil {
		return m.Ability
	}
	return nil
}

func (m *Equipment) GetCD() int32 {
	if m != nil {
		return m.CD
	}
	return 0
}

func (m *Equipment) GetUsable() int32 {
	if m != nil {
		return m.Usable
	}
	return 0
}

func (m *Equipment) GetInventory() int32 {
	if m != nil {
		return m.Inventory
	}
	return 0
}

type Ability struct {
	ATK  int32   `protobuf:"varint,1,opt,name=ATK,json=aTK" json:"ATK,omitempty"`
	DEF  int32   `protobuf:"varint,2,opt,name=DEF,json=dEF" json:"DEF,omitempty"`
	SPD  float32 `protobuf:"fixed32,3,opt,name=SPD,json=sPD" json:"SPD,omitempty"`
	TSPD float32 `protobuf:"fixed32,6,opt,name=TSPD,json=tSPD" json:"TSPD,omitempty"`
	MP   int32   `protobuf:"varint,4,opt,name=MP,json=mP" json:"MP,omitempty"`
	MAKT int32   `protobuf:"varint,5,opt,name=MAKT,json=mAKT" json:"MAKT,omitempty"`
}

func (m *Ability) Reset()                    { *m = Ability{} }
func (m *Ability) String() string            { return proto.CompactTextString(m) }
func (*Ability) ProtoMessage()               {}
func (*Ability) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *Ability) GetATK() int32 {
	if m != nil {
		return m.ATK
	}
	return 0
}

func (m *Ability) GetDEF() int32 {
	if m != nil {
		return m.DEF
	}
	return 0
}

func (m *Ability) GetSPD() float32 {
	if m != nil {
		return m.SPD
	}
	return 0
}

func (m *Ability) GetTSPD() float32 {
	if m != nil {
		return m.TSPD
	}
	return 0
}

func (m *Ability) GetMP() int32 {
	if m != nil {
		return m.MP
	}
	return 0
}

func (m *Ability) GetMAKT() int32 {
	if m != nil {
		return m.MAKT
	}
	return 0
}

func init() {
	proto.RegisterType((*Input)(nil), "msg.Input")
	proto.RegisterType((*TransForm)(nil), "msg.TransForm")
	proto.RegisterType((*Vector3)(nil), "msg.Vector3")
	proto.RegisterType((*Quaternion)(nil), "msg.Quaternion")
	proto.RegisterType((*Position)(nil), "msg.Position")
	proto.RegisterType((*CallFuncInfo)(nil), "msg.CallFuncInfo")
	proto.RegisterType((*BasicType)(nil), "msg.BasicType")
	proto.RegisterType((*Error)(nil), "msg.Error")
	proto.RegisterType((*Empty)(nil), "msg.Empty")
	proto.RegisterType((*RoomPrepareView)(nil), "msg.RoomPrepareView")
	proto.RegisterType((*GameFrame)(nil), "msg.GameFrame")
	proto.RegisterType((*RoomView)(nil), "msg.RoomView")
	proto.RegisterType((*HomeView)(nil), "msg.HomeView")
	proto.RegisterType((*RoomInfoView)(nil), "msg.RoomInfoView")
	proto.RegisterType((*RoomList)(nil), "msg.RoomList")
	proto.RegisterType((*SessionInfo)(nil), "msg.SessionInfo")
	proto.RegisterType((*Success)(nil), "msg.Success")
	proto.RegisterType((*AttrSetting)(nil), "msg.AttrSetting")
	proto.RegisterType((*SessionKey)(nil), "msg.SessionKey")
	proto.RegisterType((*ServerInfo)(nil), "msg.ServerInfo")
	proto.RegisterType((*LoginInput)(nil), "msg.LoginInput")
	proto.RegisterType((*RegistInput)(nil), "msg.RegistInput")
	proto.RegisterType((*UserInfo)(nil), "msg.UserInfo")
	proto.RegisterType((*UserState)(nil), "msg.UserState")
	proto.RegisterType((*RoomInfo)(nil), "msg.RoomInfo")
	proto.RegisterType((*Character)(nil), "msg.Character")
	proto.RegisterType((*Color)(nil), "msg.Color")
	proto.RegisterType((*Equipment)(nil), "msg.Equipment")
	proto.RegisterType((*Ability)(nil), "msg.Ability")
	proto.RegisterEnum("msg.SessionInfo_SessionState", SessionInfo_SessionState_name, SessionInfo_SessionState_value)
	proto.RegisterEnum("msg.SessionInfo_SessionCapacity", SessionInfo_SessionCapacity_name, SessionInfo_SessionCapacity_value)
	proto.RegisterEnum("msg.ServerInfo_Type", ServerInfo_Type_name, ServerInfo_Type_value)
	proto.RegisterEnum("msg.UserState_UserStatus", UserState_UserStatus_name, UserState_UserStatus_value)
	proto.RegisterEnum("msg.RoomInfo_RoomStatus", RoomInfo_RoomStatus_name, RoomInfo_RoomStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ClientToGame service

type ClientToGameClient interface {
	// roomManager
	EnterRoom(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Success, error)
	LeaveRoom(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Success, error)
	// entityManager
	PlayerInput(ctx context.Context, opts ...grpc.CallOption) (ClientToGame_PlayerInputClient, error)
	// View
	UpdateRoomPrepareView(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ClientToGame_UpdateRoomPrepareViewClient, error)
	UpdateGameFrame(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ClientToGame_UpdateGameFrameClient, error)
}

type clientToGameClient struct {
	cc *grpc.ClientConn
}

func NewClientToGameClient(cc *grpc.ClientConn) ClientToGameClient {
	return &clientToGameClient{cc}
}

func (c *clientToGameClient) EnterRoom(ctx context.Context, in *ServerInfo, opts ...grpc.CallOption) (*Success, error) {
	out := new(Success)
	err := grpc.Invoke(ctx, "/msg.ClientToGame/EnterRoom", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientToGameClient) LeaveRoom(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Success, error) {
	out := new(Success)
	err := grpc.Invoke(ctx, "/msg.ClientToGame/LeaveRoom", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientToGameClient) PlayerInput(ctx context.Context, opts ...grpc.CallOption) (ClientToGame_PlayerInputClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ClientToGame_serviceDesc.Streams[0], c.cc, "/msg.ClientToGame/PlayerInput", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientToGamePlayerInputClient{stream}
	return x, nil
}

type ClientToGame_PlayerInputClient interface {
	Send(*Input) error
	CloseAndRecv() (*Success, error)
	grpc.ClientStream
}

type clientToGamePlayerInputClient struct {
	grpc.ClientStream
}

func (x *clientToGamePlayerInputClient) Send(m *Input) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientToGamePlayerInputClient) CloseAndRecv() (*Success, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Success)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clientToGameClient) UpdateRoomPrepareView(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ClientToGame_UpdateRoomPrepareViewClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ClientToGame_serviceDesc.Streams[1], c.cc, "/msg.ClientToGame/UpdateRoomPrepareView", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientToGameUpdateRoomPrepareViewClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ClientToGame_UpdateRoomPrepareViewClient interface {
	Recv() (*RoomPrepareView, error)
	grpc.ClientStream
}

type clientToGameUpdateRoomPrepareViewClient struct {
	grpc.ClientStream
}

func (x *clientToGameUpdateRoomPrepareViewClient) Recv() (*RoomPrepareView, error) {
	m := new(RoomPrepareView)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clientToGameClient) UpdateGameFrame(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ClientToGame_UpdateGameFrameClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ClientToGame_serviceDesc.Streams[2], c.cc, "/msg.ClientToGame/UpdateGameFrame", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientToGameUpdateGameFrameClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ClientToGame_UpdateGameFrameClient interface {
	Recv() (*GameFrame, error)
	grpc.ClientStream
}

type clientToGameUpdateGameFrameClient struct {
	grpc.ClientStream
}

func (x *clientToGameUpdateGameFrameClient) Recv() (*GameFrame, error) {
	m := new(GameFrame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ClientToGame service

type ClientToGameServer interface {
	// roomManager
	EnterRoom(context.Context, *ServerInfo) (*Success, error)
	LeaveRoom(context.Context, *Empty) (*Success, error)
	// entityManager
	PlayerInput(ClientToGame_PlayerInputServer) error
	// View
	UpdateRoomPrepareView(*Empty, ClientToGame_UpdateRoomPrepareViewServer) error
	UpdateGameFrame(*Empty, ClientToGame_UpdateGameFrameServer) error
}

func RegisterClientToGameServer(s *grpc.Server, srv ClientToGameServer) {
	s.RegisterService(&_ClientToGame_serviceDesc, srv)
}

func _ClientToGame_EnterRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientToGameServer).EnterRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ClientToGame/EnterRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientToGameServer).EnterRoom(ctx, req.(*ServerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientToGame_LeaveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientToGameServer).LeaveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ClientToGame/LeaveRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientToGameServer).LeaveRoom(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientToGame_PlayerInput_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientToGameServer).PlayerInput(&clientToGamePlayerInputServer{stream})
}

type ClientToGame_PlayerInputServer interface {
	SendAndClose(*Success) error
	Recv() (*Input, error)
	grpc.ServerStream
}

type clientToGamePlayerInputServer struct {
	grpc.ServerStream
}

func (x *clientToGamePlayerInputServer) SendAndClose(m *Success) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientToGamePlayerInputServer) Recv() (*Input, error) {
	m := new(Input)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ClientToGame_UpdateRoomPrepareView_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClientToGameServer).UpdateRoomPrepareView(m, &clientToGameUpdateRoomPrepareViewServer{stream})
}

type ClientToGame_UpdateRoomPrepareViewServer interface {
	Send(*RoomPrepareView) error
	grpc.ServerStream
}

type clientToGameUpdateRoomPrepareViewServer struct {
	grpc.ServerStream
}

func (x *clientToGameUpdateRoomPrepareViewServer) Send(m *RoomPrepareView) error {
	return x.ServerStream.SendMsg(m)
}

func _ClientToGame_UpdateGameFrame_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClientToGameServer).UpdateGameFrame(m, &clientToGameUpdateGameFrameServer{stream})
}

type ClientToGame_UpdateGameFrameServer interface {
	Send(*GameFrame) error
	grpc.ServerStream
}

type clientToGameUpdateGameFrameServer struct {
	grpc.ServerStream
}

func (x *clientToGameUpdateGameFrameServer) Send(m *GameFrame) error {
	return x.ServerStream.SendMsg(m)
}

var _ClientToGame_serviceDesc = grpc.ServiceDesc{
	ServiceName: "msg.ClientToGame",
	HandlerType: (*ClientToGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnterRoom",
			Handler:    _ClientToGame_EnterRoom_Handler,
		},
		{
			MethodName: "LeaveRoom",
			Handler:    _ClientToGame_LeaveRoom_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PlayerInput",
			Handler:       _ClientToGame_PlayerInput_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UpdateRoomPrepareView",
			Handler:       _ClientToGame_UpdateRoomPrepareView_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateGameFrame",
			Handler:       _ClientToGame_UpdateGameFrame_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "message.proto",
}

// Client API for AgentToGame service

type AgentToGameClient interface {
	// SessionManager
	CreateSession(ctx context.Context, in *SessionInfo, opts ...grpc.CallOption) (*Success, error)
	GetGameServerInfo(ctx context.Context, in *SessionKey, opts ...grpc.CallOption) (*ServerInfo, error)
	GetRoomList(ctx context.Context, in *SessionKey, opts ...grpc.CallOption) (*RoomList, error)
}

type agentToGameClient struct {
	cc *grpc.ClientConn
}

func NewAgentToGameClient(cc *grpc.ClientConn) AgentToGameClient {
	return &agentToGameClient{cc}
}

func (c *agentToGameClient) CreateSession(ctx context.Context, in *SessionInfo, opts ...grpc.CallOption) (*Success, error) {
	out := new(Success)
	err := grpc.Invoke(ctx, "/msg.AgentToGame/CreateSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentToGameClient) GetGameServerInfo(ctx context.Context, in *SessionKey, opts ...grpc.CallOption) (*ServerInfo, error) {
	out := new(ServerInfo)
	err := grpc.Invoke(ctx, "/msg.AgentToGame/GetGameServerInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentToGameClient) GetRoomList(ctx context.Context, in *SessionKey, opts ...grpc.CallOption) (*RoomList, error) {
	out := new(RoomList)
	err := grpc.Invoke(ctx, "/msg.AgentToGame/GetRoomList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AgentToGame service

type AgentToGameServer interface {
	// SessionManager
	CreateSession(context.Context, *SessionInfo) (*Success, error)
	GetGameServerInfo(context.Context, *SessionKey) (*ServerInfo, error)
	GetRoomList(context.Context, *SessionKey) (*RoomList, error)
}

func RegisterAgentToGameServer(s *grpc.Server, srv AgentToGameServer) {
	s.RegisterService(&_AgentToGame_serviceDesc, srv)
}

func _AgentToGame_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentToGameServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.AgentToGame/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentToGameServer).CreateSession(ctx, req.(*SessionInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentToGame_GetGameServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentToGameServer).GetGameServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.AgentToGame/GetGameServerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentToGameServer).GetGameServerInfo(ctx, req.(*SessionKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentToGame_GetRoomList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentToGameServer).GetRoomList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.AgentToGame/GetRoomList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentToGameServer).GetRoomList(ctx, req.(*SessionKey))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentToGame_serviceDesc = grpc.ServiceDesc{
	ServiceName: "msg.AgentToGame",
	HandlerType: (*AgentToGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _AgentToGame_CreateSession_Handler,
		},
		{
			MethodName: "GetGameServerInfo",
			Handler:    _AgentToGame_GetGameServerInfo_Handler,
		},
		{
			MethodName: "GetRoomList",
			Handler:    _AgentToGame_GetRoomList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

// Client API for ClientToAgent service

type ClientToAgentClient interface {
	AquireSessionKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SessionKey, error)
	AquireOtherAgent(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerInfo, error)
	// Login
	Login(ctx context.Context, in *LoginInput, opts ...grpc.CallOption) (*UserInfo, error)
	CreateAccount(ctx context.Context, in *RegistInput, opts ...grpc.CallOption) (*Error, error)
	// UserSetting
	SetAccount(ctx context.Context, in *AttrSetting, opts ...grpc.CallOption) (*Success, error)
	SetCharacter(ctx context.Context, in *AttrSetting, opts ...grpc.CallOption) (*Success, error)
	// allocate room
	AquireGameServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerInfo, error)
	// View
	UpdateHome(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ClientToAgent_UpdateHomeClient, error)
	UpdateRoomList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ClientToAgent_UpdateRoomListClient, error)
}

type clientToAgentClient struct {
	cc *grpc.ClientConn
}

func NewClientToAgentClient(cc *grpc.ClientConn) ClientToAgentClient {
	return &clientToAgentClient{cc}
}

func (c *clientToAgentClient) AquireSessionKey(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SessionKey, error) {
	out := new(SessionKey)
	err := grpc.Invoke(ctx, "/msg.ClientToAgent/AquireSessionKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientToAgentClient) AquireOtherAgent(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerInfo, error) {
	out := new(ServerInfo)
	err := grpc.Invoke(ctx, "/msg.ClientToAgent/AquireOtherAgent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientToAgentClient) Login(ctx context.Context, in *LoginInput, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := grpc.Invoke(ctx, "/msg.ClientToAgent/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientToAgentClient) CreateAccount(ctx context.Context, in *RegistInput, opts ...grpc.CallOption) (*Error, error) {
	out := new(Error)
	err := grpc.Invoke(ctx, "/msg.ClientToAgent/CreateAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientToAgentClient) SetAccount(ctx context.Context, in *AttrSetting, opts ...grpc.CallOption) (*Success, error) {
	out := new(Success)
	err := grpc.Invoke(ctx, "/msg.ClientToAgent/SetAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientToAgentClient) SetCharacter(ctx context.Context, in *AttrSetting, opts ...grpc.CallOption) (*Success, error) {
	out := new(Success)
	err := grpc.Invoke(ctx, "/msg.ClientToAgent/SetCharacter", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientToAgentClient) AquireGameServer(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerInfo, error) {
	out := new(ServerInfo)
	err := grpc.Invoke(ctx, "/msg.ClientToAgent/AquireGameServer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientToAgentClient) UpdateHome(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ClientToAgent_UpdateHomeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ClientToAgent_serviceDesc.Streams[0], c.cc, "/msg.ClientToAgent/UpdateHome", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientToAgentUpdateHomeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ClientToAgent_UpdateHomeClient interface {
	Recv() (*HomeView, error)
	grpc.ClientStream
}

type clientToAgentUpdateHomeClient struct {
	grpc.ClientStream
}

func (x *clientToAgentUpdateHomeClient) Recv() (*HomeView, error) {
	m := new(HomeView)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clientToAgentClient) UpdateRoomList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (ClientToAgent_UpdateRoomListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ClientToAgent_serviceDesc.Streams[1], c.cc, "/msg.ClientToAgent/UpdateRoomList", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientToAgentUpdateRoomListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ClientToAgent_UpdateRoomListClient interface {
	Recv() (*RoomList, error)
	grpc.ClientStream
}

type clientToAgentUpdateRoomListClient struct {
	grpc.ClientStream
}

func (x *clientToAgentUpdateRoomListClient) Recv() (*RoomList, error) {
	m := new(RoomList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ClientToAgent service

type ClientToAgentServer interface {
	AquireSessionKey(context.Context, *Empty) (*SessionKey, error)
	AquireOtherAgent(context.Context, *Empty) (*ServerInfo, error)
	// Login
	Login(context.Context, *LoginInput) (*UserInfo, error)
	CreateAccount(context.Context, *RegistInput) (*Error, error)
	// UserSetting
	SetAccount(context.Context, *AttrSetting) (*Success, error)
	SetCharacter(context.Context, *AttrSetting) (*Success, error)
	// allocate room
	AquireGameServer(context.Context, *Empty) (*ServerInfo, error)
	// View
	UpdateHome(*Empty, ClientToAgent_UpdateHomeServer) error
	UpdateRoomList(*Empty, ClientToAgent_UpdateRoomListServer) error
}

func RegisterClientToAgentServer(s *grpc.Server, srv ClientToAgentServer) {
	s.RegisterService(&_ClientToAgent_serviceDesc, srv)
}

func _ClientToAgent_AquireSessionKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientToAgentServer).AquireSessionKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ClientToAgent/AquireSessionKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientToAgentServer).AquireSessionKey(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientToAgent_AquireOtherAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientToAgentServer).AquireOtherAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ClientToAgent/AquireOtherAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientToAgentServer).AquireOtherAgent(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientToAgent_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientToAgentServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ClientToAgent/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientToAgentServer).Login(ctx, req.(*LoginInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientToAgent_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientToAgentServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ClientToAgent/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientToAgentServer).CreateAccount(ctx, req.(*RegistInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientToAgent_SetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttrSetting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientToAgentServer).SetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ClientToAgent/SetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientToAgentServer).SetAccount(ctx, req.(*AttrSetting))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientToAgent_SetCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttrSetting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientToAgentServer).SetCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ClientToAgent/SetCharacter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientToAgentServer).SetCharacter(ctx, req.(*AttrSetting))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientToAgent_AquireGameServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientToAgentServer).AquireGameServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.ClientToAgent/AquireGameServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientToAgentServer).AquireGameServer(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientToAgent_UpdateHome_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClientToAgentServer).UpdateHome(m, &clientToAgentUpdateHomeServer{stream})
}

type ClientToAgent_UpdateHomeServer interface {
	Send(*HomeView) error
	grpc.ServerStream
}

type clientToAgentUpdateHomeServer struct {
	grpc.ServerStream
}

func (x *clientToAgentUpdateHomeServer) Send(m *HomeView) error {
	return x.ServerStream.SendMsg(m)
}

func _ClientToAgent_UpdateRoomList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClientToAgentServer).UpdateRoomList(m, &clientToAgentUpdateRoomListServer{stream})
}

type ClientToAgent_UpdateRoomListServer interface {
	Send(*RoomList) error
	grpc.ServerStream
}

type clientToAgentUpdateRoomListServer struct {
	grpc.ServerStream
}

func (x *clientToAgentUpdateRoomListServer) Send(m *RoomList) error {
	return x.ServerStream.SendMsg(m)
}

var _ClientToAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "msg.ClientToAgent",
	HandlerType: (*ClientToAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AquireSessionKey",
			Handler:    _ClientToAgent_AquireSessionKey_Handler,
		},
		{
			MethodName: "AquireOtherAgent",
			Handler:    _ClientToAgent_AquireOtherAgent_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ClientToAgent_Login_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _ClientToAgent_CreateAccount_Handler,
		},
		{
			MethodName: "SetAccount",
			Handler:    _ClientToAgent_SetAccount_Handler,
		},
		{
			MethodName: "SetCharacter",
			Handler:    _ClientToAgent_SetCharacter_Handler,
		},
		{
			MethodName: "AquireGameServer",
			Handler:    _ClientToAgent_AquireGameServer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateHome",
			Handler:       _ClientToAgent_UpdateHome_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateRoomList",
			Handler:       _ClientToAgent_UpdateRoomList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "message.proto",
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xcf, 0x6e, 0x1b, 0xc9,
	0xd1, 0xe7, 0x70, 0x38, 0x24, 0xa7, 0x28, 0x52, 0x74, 0xc3, 0xdf, 0x07, 0x9a, 0x58, 0x27, 0xda,
	0x89, 0xb1, 0xab, 0x8d, 0x37, 0xb4, 0x2d, 0x07, 0xd9, 0x60, 0xe1, 0x3d, 0xd0, 0x14, 0x25, 0x0b,
	0x12, 0x2d, 0x66, 0x48, 0x7b, 0x93, 0x5c, 0x82, 0x11, 0xd9, 0xa2, 0x07, 0x9e, 0x99, 0xe6, 0xce,
	0xf4, 0x48, 0x62, 0x6e, 0x01, 0x02, 0xe4, 0x94, 0x6b, 0x80, 0xbc, 0x40, 0x0e, 0x79, 0x8e, 0x9c,
	0x72, 0x0f, 0xf2, 0x08, 0x79, 0x83, 0x9c, 0x83, 0xaa, 0xee, 0x19, 0x0e, 0x29, 0x6d, 0x6c, 0xe4,
	0xc4, 0xa9, 0xbf, 0xec, 0xaa, 0xfa, 0x55, 0x75, 0x35, 0x34, 0x43, 0x9e, 0x24, 0xde, 0x82, 0xf7,
	0x96, 0xb1, 0x90, 0x82, 0x99, 0x61, 0xb2, 0xe8, 0xda, 0x5e, 0xb4, 0x52, 0xb4, 0xf3, 0x0f, 0x03,
	0xac, 0x93, 0x68, 0x99, 0x4a, 0xf6, 0xff, 0x50, 0x7d, 0x93, 0xf0, 0xf8, 0x64, 0xde, 0x31, 0xf6,
	0x8c, 0x7d, 0xd3, 0xad, 0xa6, 0x44, 0xb1, 0x87, 0x00, 0xaf, 0x7e, 0x33, 0x12, 0x57, 0x3c, 0xe4,
	0x91, 0xec, 0x94, 0xf7, 0x8c, 0xfd, 0xb2, 0x6b, 0xbf, 0xcb, 0x18, 0x28, 0x7e, 0xbb, 0x16, 0x9b,
	0x4a, 0x7c, 0x95, 0x8b, 0x3f, 0x01, 0x7b, 0xf2, 0xde, 0x0f, 0x82, 0xd7, 0x5e, 0xc8, 0x3b, 0xd6,
	0x9e, 0xb1, 0x6f, 0xbb, 0x76, 0x92, 0x31, 0xd8, 0x0f, 0x00, 0x48, 0x7a, 0x24, 0xe2, 0x19, 0xef,
	0x54, 0xc8, 0x18, 0x92, 0x9c, 0x83, 0xd6, 0x53, 0x3f, 0xe4, 0x13, 0xe9, 0x85, 0xcb, 0x4e, 0x95,
	0x8e, 0x65, 0xcb, 0x8c, 0xc1, 0xba, 0x50, 0x77, 0xd3, 0x28, 0xf2, 0x17, 0xaf, 0x45, 0xa7, 0x46,
	0xc2, 0x7a, 0xac, 0x69, 0xe7, 0x02, 0xec, 0x69, 0xec, 0x45, 0xc9, 0x91, 0x88, 0x43, 0xb6, 0x0f,
	0xf5, 0xb1, 0x48, 0x7c, 0xe9, 0x8b, 0x88, 0x82, 0x6b, 0x1c, 0xec, 0xf4, 0xc2, 0x64, 0xd1, 0x7b,
	0xcb, 0x67, 0x52, 0xc4, 0xcf, 0xdd, 0xfa, 0x52, 0x4b, 0xd9, 0x63, 0xa8, 0xbb, 0x42, 0x7a, 0xa4,
	0x59, 0x26, 0xcd, 0x5d, 0xd2, 0xfc, 0x45, 0xea, 0x49, 0x1e, 0x47, 0xbe, 0x88, 0xdc, 0x7a, 0xac,
	0x15, 0x9c, 0xe7, 0x50, 0xd3, 0x1e, 0xd8, 0x0e, 0x18, 0xbf, 0x24, 0xd7, 0x86, 0x6b, 0xdc, 0x20,
	0xf5, 0x2b, 0x32, 0x37, 0x5c, 0x63, 0x85, 0xd4, 0xaf, 0x29, 0x31, 0x86, 0x6b, 0xfc, 0xd6, 0x39,
	0x04, 0x58, 0x3b, 0xfb, 0x78, 0x3b, 0xa4, 0xbe, 0xa5, 0x0c, 0x19, 0xae, 0x71, 0xed, 0xfc, 0xc5,
	0x58, 0x87, 0xc4, 0x9e, 0x41, 0x75, 0x2c, 0x92, 0x91, 0xb7, 0xec, 0x18, 0x7b, 0xe6, 0x7e, 0xe3,
	0xe0, 0x01, 0x1d, 0x39, 0x13, 0xf7, 0x94, 0x6c, 0x18, 0xc9, 0x78, 0xe5, 0x56, 0x97, 0x44, 0x6c,
	0x26, 0xb6, 0xbc, 0x95, 0xd8, 0xee, 0x09, 0x34, 0x0a, 0x46, 0xac, 0x0d, 0xe6, 0x7b, 0xbe, 0xd2,
	0xb0, 0xc0, 0x4f, 0xf6, 0x08, 0xac, 0x2b, 0x2f, 0x48, 0xb9, 0xce, 0x51, 0x8b, 0xfe, 0x30, 0xcf,
	0xb7, 0xab, 0x84, 0x5f, 0x97, 0x7f, 0x6e, 0x38, 0x7f, 0x2f, 0xc3, 0xce, 0xc0, 0x0b, 0x82, 0xa3,
	0x34, 0x9a, 0x9d, 0x44, 0x97, 0x62, 0xa3, 0x68, 0x06, 0xe1, 0x21, 0x2f, 0x1a, 0xca, 0xa6, 0x5e,
	0xbc, 0xe0, 0xf2, 0x64, 0xae, 0x0f, 0x55, 0x97, 0x9a, 0x46, 0x78, 0x1e, 0xc5, 0x22, 0x3c, 0x99,
	0x53, 0x12, 0x4c, 0xb7, 0x7a, 0x49, 0xd4, 0x66, 0x24, 0xd6, 0x36, 0x44, 0x18, 0x54, 0xf0, 0x9f,
	0x09, 0x3b, 0xb6, 0x5b, 0xb9, 0x4c, 0xa3, 0x19, 0xdb, 0x87, 0x1a, 0x7a, 0x1a, 0x8b, 0x84, 0x50,
	0x73, 0xfb, 0xf8, 0xb5, 0x4b, 0x25, 0xc6, 0x30, 0xa7, 0x02, 0xf5, 0xea, 0x77, 0x87, 0x29, 0x51,
	0xc8, 0xee, 0x83, 0xf5, 0x96, 0x92, 0x61, 0x13, 0x7e, 0x55, 0xf0, 0xec, 0xc7, 0x60, 0x8d, 0xbd,
	0xd8, 0x0b, 0x3b, 0x40, 0x35, 0xb9, 0xdf, 0x5b, 0x08, 0xb1, 0x08, 0x74, 0x1b, 0x5e, 0xa4, 0x97,
	0xbd, 0x7e, 0xb4, 0x72, 0xad, 0x25, 0xaa, 0xb0, 0xcf, 0xa0, 0x4a, 0xba, 0x49, 0xa7, 0x41, 0xca,
	0xea, 0x8f, 0x5e, 0x7a, 0x89, 0x3f, 0x9b, 0xae, 0x96, 0xdc, 0xad, 0x92, 0x5a, 0xe2, 0xfc, 0xd9,
	0x00, 0x3b, 0xe7, 0xb2, 0x16, 0x18, 0x13, 0x95, 0xc2, 0x57, 0x25, 0xd7, 0x48, 0x90, 0x3e, 0x53,
	0x69, 0x43, 0x3a, 0x40, 0xfa, 0x48, 0x35, 0x24, 0xd2, 0x97, 0x48, 0x9f, 0x50, 0xf2, 0x2c, 0xa4,
	0x7d, 0xa4, 0x5f, 0x52, 0xc6, 0xea, 0x48, 0x5f, 0x20, 0x7d, 0x48, 0x89, 0x32, 0x90, 0x9e, 0xb3,
	0x47, 0x60, 0xf4, 0x75, 0x86, 0xee, 0x3c, 0x3d, 0x6a, 0x79, 0x2f, 0xab, 0x50, 0x39, 0xf4, 0xa4,
	0xe7, 0x84, 0x60, 0x0d, 0xe3, 0x58, 0xc4, 0xac, 0x03, 0xb5, 0x61, 0x1c, 0xe3, 0x09, 0x75, 0x7d,
	0x6b, 0x5c, 0x91, 0x58, 0xc2, 0x61, 0x1c, 0x8f, 0x92, 0x05, 0x9d, 0xd2, 0x76, 0xab, 0x9c, 0xa8,
	0x0d, 0x48, 0x98, 0x5b, 0x90, 0xf8, 0x9e, 0xb2, 0x3b, 0x35, 0xb0, 0x86, 0xe1, 0x52, 0xae, 0x9c,
	0x7b, 0xb0, 0xeb, 0x0a, 0x11, 0x8e, 0x63, 0xbe, 0xf4, 0x62, 0xfe, 0xd6, 0xe7, 0xd7, 0x4e, 0x03,
	0xec, 0x63, 0x2f, 0xe4, 0x47, 0xb1, 0x17, 0x72, 0x07, 0xb0, 0xa3, 0x45, 0x48, 0x02, 0x80, 0xfa,
	0x2b, 0x11, 0x2a, 0xa5, 0x16, 0xec, 0x20, 0x1f, 0x31, 0x49, 0xf4, 0x4f, 0x94, 0xde, 0x99, 0x9f,
	0x48, 0xf6, 0x29, 0x54, 0x7c, 0xc9, 0x43, 0xdd, 0x4e, 0x4d, 0xaa, 0x46, 0xa6, 0xec, 0x92, 0xc8,
	0xf9, 0xa3, 0x09, 0x8d, 0x09, 0x4f, 0x12, 0x5f, 0x44, 0x04, 0xeb, 0xe7, 0x60, 0x4d, 0xa4, 0x27,
	0x55, 0xcc, 0xad, 0x83, 0x87, 0x64, 0x53, 0x50, 0xc8, 0xbe, 0x49, 0xc9, 0xb5, 0x12, 0xfc, 0x61,
	0x2f, 0xa0, 0x3e, 0xf0, 0x96, 0xde, 0xcc, 0x97, 0x2b, 0x4a, 0x49, 0xeb, 0x60, 0xef, 0xfb, 0xec,
	0x32, 0x3d, 0xb7, 0x3e, 0xd3, 0x5f, 0x88, 0xed, 0x37, 0xa9, 0x3f, 0xd7, 0xa0, 0xaf, 0xa4, 0xa9,
	0x3f, 0x67, 0x9f, 0x82, 0x79, 0xca, 0x57, 0x94, 0xc5, 0x6c, 0x74, 0x69, 0x07, 0xa7, 0x7c, 0xa5,
	0x7a, 0xf7, 0x0b, 0xa8, 0xd3, 0x9c, 0x8f, 0x2e, 0x05, 0xe5, 0x34, 0x0b, 0x30, 0x63, 0xba, 0xf5,
	0x54, 0x7f, 0x39, 0x73, 0xd8, 0x29, 0x1e, 0x9b, 0x35, 0xc1, 0x7e, 0x2d, 0x34, 0xa7, 0x5d, 0x62,
	0x36, 0x58, 0xc7, 0x29, 0x4f, 0x64, 0xdb, 0x60, 0x3b, 0xda, 0xe9, 0x3c, 0xe0, 0xed, 0x32, 0x6b,
	0x01, 0x28, 0x6f, 0x98, 0xb4, 0xb6, 0xc9, 0x76, 0xa1, 0xf1, 0xad, 0xe7, 0xcb, 0xa9, 0x98, 0x48,
	0x2f, 0x96, 0xed, 0x0a, 0x6b, 0x40, 0x6d, 0x1c, 0x78, 0x2b, 0x3f, 0x5a, 0xb4, 0x2d, 0x67, 0x00,
	0xbb, 0x5b, 0x41, 0xb2, 0x2a, 0x94, 0x8f, 0x47, 0xed, 0x12, 0x3a, 0x42, 0x17, 0x23, 0x2f, 0x91,
	0x3c, 0x6e, 0x1b, 0x19, 0x3d, 0x08, 0x7c, 0x1e, 0xc9, 0x76, 0x99, 0xd5, 0xa1, 0xf2, 0x5a, 0x44,
	0xbc, 0x6d, 0x3a, 0x0f, 0xa0, 0x36, 0x49, 0x67, 0x33, 0x9e, 0x60, 0x1f, 0x94, 0xc5, 0x7b, 0xaa,
	0x43, 0xdd, 0x2d, 0x8b, 0xf7, 0xce, 0x08, 0x1a, 0x7d, 0x29, 0xe3, 0x09, 0x97, 0xd2, 0x8f, 0x16,
	0x88, 0xa8, 0x11, 0x97, 0xef, 0xc4, 0x5c, 0xc3, 0xb3, 0x1a, 0x12, 0x85, 0x53, 0x0e, 0x53, 0xa7,
	0xa0, 0x49, 0x99, 0xca, 0x1b, 0x5b, 0x81, 0x52, 0x35, 0xb6, 0xe3, 0x00, 0xac, 0x53, 0xba, 0xd6,
	0x31, 0x8a, 0x3a, 0x7f, 0x2a, 0xa3, 0x52, 0x7c, 0xa5, 0xf2, 0xc8, 0x7e, 0x9a, 0x51, 0x79, 0x57,
	0xb4, 0x0e, 0xee, 0xeb, 0xe2, 0x64, 0x4a, 0x3d, 0xea, 0x74, 0x48, 0x72, 0x3d, 0x9c, 0x6c, 0xe3,
	0xf4, 0x22, 0xf0, 0x67, 0xeb, 0x63, 0xd9, 0xcb, 0x8c, 0x81, 0xd5, 0x1f, 0x8b, 0x58, 0xea, 0xb3,
	0x55, 0x96, 0x22, 0x96, 0xc8, 0xeb, 0xcf, 0xe7, 0x31, 0x95, 0xd5, 0x76, 0x2b, 0xde, 0x7c, 0x1e,
	0xb3, 0x27, 0xc5, 0xe3, 0x12, 0x56, 0xee, 0x00, 0x06, 0x24, 0xeb, 0x88, 0x3a, 0x50, 0x1b, 0x79,
	0x37, 0x03, 0x11, 0x45, 0xfa, 0xc6, 0xad, 0x85, 0x8a, 0x44, 0xc9, 0x6b, 0x71, 0x4d, 0x12, 0x75,
	0xdd, 0xd6, 0x22, 0x45, 0x3a, 0x9f, 0x43, 0x45, 0x8f, 0x24, 0xc0, 0xce, 0x53, 0x51, 0xb5, 0x4b,
	0x58, 0xf8, 0xfe, 0x82, 0x47, 0x52, 0x33, 0x0c, 0xe7, 0x05, 0xc0, 0x99, 0x58, 0xf8, 0x91, 0x5a,
	0x39, 0xba, 0x0a, 0x35, 0xb4, 0x1b, 0xe8, 0xbb, 0x20, 0xd5, 0x34, 0xc5, 0x97, 0x5c, 0xcf, 0x75,
	0xe0, 0x95, 0x65, 0x72, 0x3d, 0x77, 0x26, 0xd0, 0x70, 0xf9, 0xc2, 0x4f, 0xe4, 0xff, 0x64, 0x8e,
	0xb5, 0x1a, 0x86, 0x9e, 0x1f, 0x64, 0xf5, 0xe4, 0x48, 0x38, 0xff, 0x36, 0xd6, 0x0d, 0xf1, 0x21,
	0x97, 0xd4, 0x6f, 0xe5, 0x42, 0xbf, 0x0d, 0x60, 0xe7, 0xfc, 0x3a, 0x1a, 0xbc, 0xf3, 0x62, 0x6f,
	0x26, 0x79, 0xdc, 0x31, 0x69, 0x62, 0xfc, 0x70, 0xa3, 0xa1, 0x7a, 0x45, 0x0d, 0x75, 0x0d, 0xef,
	0x88, 0x02, 0x8b, 0x3d, 0x82, 0xe6, 0x9b, 0x84, 0xcf, 0xd7, 0x5e, 0xd4, 0xa8, 0x6b, 0xa6, 0x45,
	0x66, 0xf7, 0x1c, 0xee, 0xdd, 0x72, 0xf4, 0xb1, 0x57, 0x73, 0x6e, 0x55, 0xbc, 0x9a, 0x7f, 0x67,
	0x80, 0x8d, 0x67, 0x54, 0xbd, 0xfd, 0x64, 0x73, 0x80, 0x3d, 0xc8, 0x43, 0x20, 0x6e, 0xfe, 0x95,
	0x26, 0x7a, 0x78, 0x39, 0x03, 0xd5, 0xe4, 0x8a, 0x89, 0x95, 0x3f, 0x8f, 0x06, 0x31, 0xf7, 0xb0,
	0xc7, 0xd4, 0x6c, 0xa0, 0x42, 0xb7, 0x0d, 0x6c, 0xf6, 0xf3, 0xcb, 0xcb, 0xc0, 0x8f, 0x70, 0x34,
	0x34, 0xc1, 0x3e, 0x8f, 0xb2, 0xde, 0x37, 0x9d, 0x3f, 0x54, 0xd4, 0xd8, 0xa5, 0xe4, 0x67, 0x09,
	0x36, 0x0a, 0x09, 0x66, 0x50, 0xa1, 0x62, 0xe8, 0x3a, 0x46, 0x58, 0x88, 0x2e, 0xd4, 0x11, 0x65,
	0xd4, 0x4c, 0xfa, 0xbe, 0x58, 0x68, 0x1a, 0x9b, 0xe6, 0xfc, 0x3a, 0xe2, 0x31, 0x39, 0x52, 0x79,
	0xb4, 0x45, 0xc6, 0x60, 0xdf, 0x14, 0x07, 0x53, 0xc7, 0xa2, 0x62, 0x3d, 0xdc, 0x18, 0xef, 0xbd,
	0xb5, 0x5c, 0x95, 0x0a, 0xd2, 0x9c, 0xc1, 0xbe, 0x06, 0xdb, 0xe5, 0xde, 0x7c, 0x85, 0x3a, 0x9d,
	0x2a, 0x59, 0x7f, 0xb2, 0x69, 0x9d, 0x8b, 0x95, 0xb1, 0x1d, 0x67, 0x34, 0x7b, 0x0a, 0x55, 0x95,
	0x2a, 0xea, 0x9d, 0xd6, 0x41, 0x67, 0xcb, 0x50, 0x88, 0x50, 0xe7, 0xb7, 0x9a, 0xa8, 0x94, 0xee,
	0xc3, 0xee, 0x19, 0xbf, 0x94, 0x23, 0x3f, 0x08, 0xfc, 0x09, 0x9f, 0x89, 0x68, 0x4e, 0x7b, 0x88,
	0xe9, 0xee, 0x06, 0x9b, 0xec, 0xee, 0x19, 0xec, 0x6e, 0x1d, 0xfb, 0x0e, 0x60, 0xfc, 0x68, 0x13,
	0x18, 0x5b, 0x43, 0x7f, 0x8d, 0x8b, 0xee, 0x0b, 0x68, 0x6d, 0x86, 0x71, 0x87, 0xb3, 0xfb, 0x45,
	0x67, 0xf5, 0x22, 0xaa, 0x7e, 0xa6, 0x46, 0xb4, 0x86, 0x45, 0x13, 0x6c, 0x75, 0x33, 0x2b, 0x54,
	0x6c, 0x54, 0xdf, 0x60, 0x00, 0xd5, 0x61, 0x34, 0xc7, 0xef, 0xb2, 0xf3, 0x2f, 0x13, 0xec, 0x75,
	0x4b, 0xdc, 0x05, 0x85, 0x47, 0xd0, 0xcc, 0x15, 0xa8, 0xf6, 0x0a, 0x13, 0xcd, 0x59, 0x91, 0x99,
	0x03, 0xc6, 0x2c, 0x00, 0x66, 0x0f, 0xac, 0x81, 0x08, 0x44, 0xac, 0xef, 0x3b, 0x50, 0x3d, 0x81,
	0x1c, 0xd7, 0x9a, 0xe1, 0x0f, 0xc6, 0x73, 0xc6, 0xaf, 0x78, 0x40, 0x03, 0xd2, 0x72, 0xad, 0x00,
	0x09, 0x8c, 0x7b, 0x78, 0xa3, 0x1e, 0x1e, 0x96, 0x6b, 0xf2, 0x1b, 0xda, 0x9b, 0x47, 0xde, 0xcd,
	0x2b, 0xee, 0x05, 0xf2, 0x5d, 0x07, 0xd4, 0x63, 0x27, 0xcc, 0x18, 0xec, 0x33, 0xa8, 0xf5, 0x2f,
	0xfc, 0x00, 0xaf, 0xf3, 0x5a, 0xe1, 0x99, 0xa1, 0x79, 0x6e, 0xcd, 0x53, 0x1f, 0xec, 0x10, 0x76,
	0x86, 0xdf, 0xa5, 0xfe, 0x12, 0x5f, 0x48, 0xb8, 0xb6, 0xd7, 0x09, 0x4a, 0x7b, 0x9b, 0xad, 0xda,
	0x2b, 0xaa, 0xe8, 0xb1, 0xc1, 0x0b, 0x2c, 0xf6, 0x25, 0x54, 0xf0, 0x5e, 0xeb, 0xd8, 0x64, 0xdd,
	0xd9, 0xb2, 0x46, 0x91, 0xb2, 0xaa, 0x78, 0x52, 0xd2, 0xf8, 0xb8, 0xe5, 0xf0, 0x63, 0xc7, 0x47,
	0x6e, 0x58, 0x84, 0xc9, 0x57, 0x60, 0xe7, 0xff, 0x51, 0x74, 0x64, 0xdf, 0x81, 0x90, 0x72, 0x11,
	0x21, 0xcf, 0x74, 0x35, 0xf0, 0x49, 0xe3, 0x92, 0x89, 0xe5, 0x1a, 0x44, 0x1d, 0x93, 0xb2, 0xe5,
	0x1a, 0x0b, 0xa4, 0x5e, 0x52, 0x0d, 0x2d, 0xd7, 0xb8, 0x70, 0xfe, 0x69, 0x80, 0x9d, 0x1f, 0x22,
	0x2f, 0xb1, 0x51, 0x28, 0x31, 0x53, 0x37, 0x50, 0x36, 0x27, 0xa4, 0x86, 0x02, 0x81, 0xc8, 0x2c,
	0x80, 0xe8, 0xc3, 0x50, 0x28, 0x14, 0xd1, 0xfa, 0x6f, 0x45, 0x6c, 0x41, 0x79, 0x70, 0xa8, 0xb1,
	0x51, 0x9e, 0x1d, 0xaa, 0xf7, 0xb3, 0x77, 0x11, 0x70, 0xaa, 0xbd, 0x85, 0xef, 0x67, 0xa4, 0x10,
	0x32, 0x27, 0xd1, 0x15, 0x8f, 0xa4, 0x88, 0x57, 0xd4, 0xc0, 0x96, 0x6b, 0xfb, 0x19, 0xc3, 0xb9,
	0xce, 0xff, 0x0d, 0x73, 0xd8, 0x9f, 0x9e, 0xea, 0x84, 0x98, 0xde, 0xf4, 0x14, 0x39, 0x87, 0xc3,
	0x23, 0x9d, 0x14, 0x73, 0x3e, 0x3c, 0x42, 0xce, 0x64, 0x7c, 0xa8, 0x9f, 0xd9, 0x66, 0x32, 0x3e,
	0xa4, 0xc0, 0x91, 0x55, 0x25, 0x56, 0x45, 0x4e, 0xc6, 0x87, 0x78, 0xb4, 0xd1, 0x58, 0xad, 0xfa,
	0x6e, 0x39, 0x1c, 0xa3, 0xce, 0xa8, 0x7f, 0x3a, 0xd5, 0xe0, 0xae, 0x84, 0xfd, 0xd3, 0xe9, 0xc1,
	0xef, 0xf1, 0x61, 0x46, 0x7b, 0xd4, 0x54, 0xe0, 0x34, 0x65, 0x5f, 0x82, 0x3d, 0x8c, 0xf0, 0x8a,
	0xc0, 0x49, 0xb7, 0xbb, 0xb5, 0x9d, 0x74, 0x55, 0x12, 0xf4, 0x8a, 0xe5, 0x94, 0xd8, 0xe7, 0x60,
	0x9f, 0x71, 0xef, 0x8a, 0x93, 0xb6, 0xca, 0x22, 0xed, 0xe3, 0xb7, 0x14, 0x1f, 0x43, 0x03, 0x1b,
	0x1e, 0xdd, 0xe0, 0x9d, 0xad, 0x54, 0xe9, 0x7b, 0x5b, 0x75, 0xdf, 0x60, 0xdf, 0xc0, 0xff, 0xbd,
	0x59, 0xce, 0x71, 0x43, 0xde, 0x5c, 0xe9, 0x37, 0xfe, 0xe1, 0x7e, 0x3e, 0x39, 0x8b, 0x4b, 0x7f,
	0xe9, 0xa9, 0xc1, 0x9e, 0xc1, 0xae, 0x32, 0xcf, 0xd7, 0xff, 0x0d, 0x43, 0x05, 0xe6, 0xf5, 0xd3,
	0xa0, 0xf4, 0xd4, 0x38, 0xf8, 0xab, 0xa1, 0x57, 0x14, 0x9d, 0x85, 0x67, 0xd0, 0xa4, 0x5b, 0x8c,
	0xeb, 0xed, 0x88, 0xb5, 0xb7, 0x37, 0xf2, 0x5b, 0x11, 0x7e, 0x05, 0xf7, 0x8e, 0xb9, 0x5c, 0xef,
	0x3d, 0x74, 0x97, 0x6d, 0xaf, 0x58, 0xdd, 0xed, 0x8c, 0x3a, 0x25, 0xf6, 0x04, 0x1a, 0xc7, 0x5c,
	0xe6, 0xaf, 0x8e, 0x5b, 0x26, 0xeb, 0x87, 0x07, 0xca, 0x9d, 0xd2, 0xc1, 0xdf, 0x4c, 0x68, 0x66,
	0x35, 0xa3, 0x43, 0xb3, 0x67, 0xd0, 0xee, 0x7f, 0x97, 0xfa, 0x31, 0x2f, 0xac, 0xa4, 0xc5, 0x90,
	0xb7, 0x7d, 0x3a, 0xa5, 0xb5, 0xc9, 0xb9, 0x7c, 0xc7, 0x63, 0xe5, 0xe6, 0x2e, 0x93, 0xc2, 0x41,
	0xbf, 0xd0, 0x97, 0xb9, 0x3e, 0xe2, 0x7a, 0x83, 0xeb, 0x6e, 0xde, 0x22, 0x14, 0x93, 0xce, 0x5f,
	0x7f, 0x36, 0x13, 0x69, 0x24, 0x75, 0xfe, 0x0a, 0x6b, 0x5b, 0x57, 0xff, 0x19, 0x3e, 0x16, 0x9d,
	0x12, 0xeb, 0xe1, 0x7e, 0x2a, 0x37, 0xb5, 0x0b, 0xeb, 0xfa, 0xad, 0x6c, 0x3f, 0xc5, 0x37, 0x89,
	0x5c, 0xdf, 0x14, 0x1f, 0xb6, 0xc8, 0x03, 0x5e, 0x97, 0xe8, 0x43, 0x01, 0x3f, 0x06, 0x50, 0x40,
	0xc2, 0xe7, 0xe2, 0x86, 0xb2, 0x0a, 0x38, 0x7f, 0x45, 0x22, 0xea, 0x9e, 0x40, 0x6b, 0x0d, 0x5a,
	0xaa, 0xe4, 0x6d, 0x83, 0x75, 0x11, 0x9f, 0x1a, 0x17, 0x55, 0x7a, 0x45, 0x3f, 0xff, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xfb, 0x4e, 0x2f, 0x26, 0x9b, 0x13, 0x00, 0x00,
}
